{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "app-hpa.fullname" . }}
  labels:
    {{- include "app-hpa.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "app-hpa.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Pods
      pods:
        metric:
          name: sum_http_server_requests_seconds_count_filted
        target:
          type: AverageValue
          averageValue: {{ .Values.autoscaling.targetHttpRequestCount }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.scaleDown.stabilizationWindowSeconds }}
      policies:
      - type: Pods
        value: {{ .Values.autoscaling.scaleDown.pods }}
        periodSeconds: {{ .Values.autoscaling.scaleDown.periodSeconds }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.scaleUp.stabilizationWindowSeconds }}
      policies:
      - type: Pods
        value: {{ .Values.autoscaling.scaleUp.pods }}
        periodSeconds: {{ .Values.autoscaling.scaleUp.periodSeconds }}
      selectPolicy: Max
{{- end }}
